### ISSUE TITLE
Validation results for CULane

### ISSUE THREAD

**Issue by AirSmoke031** [voldemortX/pytorch-auto-drive#57] opened 2022-02-02 11:37 UTC
Hello, first things first, nice job on the project.

I managed to replicate the TEST results from the repos. I downloaded trained models then tested them and got good results.
However, for validation of CULane I get bad results. I saw that a guy had a simillar problem but I couldnt solve it like he did.

So my base CULane dataset is at "/home/grgur/CULane/" and I have all the needed files.
In my output folder there  is 3 driver directories that were generated by the test and they contain the .txt files.
The output folder should be located at /home/grgur/pytorch-auto-drive/tools/culane_evaluation so the relative path for detect_dir should be okay.

Its probably a pathing problem but I cant see it.

Here is my output:
`>(voldemort) grgur@MCS90:~/pytorch-auto-drive$ ./autotest_culane.sh resnet34_scnn_culane val checkpoints
experiment name: resnet34_scnn_culane
status: val
save dir: checkpoints
------------Configuration---------
anno_dir: /home/grgur/CULane/
detect_dir: ../../output/
im_dir: /home/grgur/CULane/
list_im_file: /home/grgur/CULane/list/val.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 0 fn: 32682
no positive detection
finished process file
precision: -1
recall: 0
Fmeasure: 0
------------`

For my eval_validation file its
#!/bin/bash
root=../../
data_dir=/home/grgur/CULane/
exp=$1
detect_dir=../../output/

# These can not be changed
w_lane=30;
iou=0.5;  # Set iou to 0.3 or 0.5
im_w=1640
im_h=590
frame=1
list=${data_dir}list/val.txt
out=./output/${exp}_iou${iou}_validation.txt
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out

if ! [ -z "$2" ]
  then
    mkdir -p ../../${2}/${1}
    cp ${out} ../../${2}/${1}/val_result.txt
fi

**Comment by voldemortX** [comment] 2022-02-02 12:38
@AirSmoke031 I can't see a pathing problem here. Can you check and see if there are predictions on val set? It should be in `/home/grgur/pytorch-auto-drive/outputs/driver_23_30frame`. If not, you need to run `python main_landet.py --val --config=xxx` first.

**Comment by AirSmoke031** [comment] 2022-02-02 12:59
Yes they are there, for confirmation one is on  /home/grgur/pytorch-auto-drive/output/driver_37_30frame/05181432_0203.MP4/02220.lines.txt for instance.

**Comment by voldemortX** [comment] 2022-02-02 13:17
could you try use all relative paths? Like `data_dir=../../../CULane/`? I'm trying to reproduce this problem but It seems alright on my part.

**Comment by AirSmoke031** [comment] 2022-02-02 13:25
I had to go from my workstation. I will do what you asked from me..do some reruns then I will come back to you.
Thank you for your time and swift response. <3

**Comment by AirSmoke031** [comment] 2022-02-03 07:53
I resolved the issuse.
The problem was with the relative path for the detect_dir. I probably didnt follow the instructions well so I messed up the relative pathing that was premade.

What I did is just gave the full path to the output for detect_dir as you can see and I got the results.

Thank you for everything. 

xperiment name: resnet34_scnn_culane
status: val
save dir: checkpoints
------------Configuration---------
anno_dir: /home/grgur/CULane/
detect_dir: /home/grgur/pytorch-auto-drive/output/
im_dir: /home/grgur/CULane/
list_im_file: /home/grgur/CULane/list/val.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 24339 fp: 7252 fn: 8343
finished process file
precision: 0.770441
recall: 0.744722
Fmeasure: 0.757363
---------------------

**Comment by voldemortX** [comment] 2022-02-03 08:19
That is good to hear.  You are welcome!

**Comment by voldemortX** [comment] 2022-02-03 12:10
Since the problem is resolved, I'll close it. Feel free to reopen.

Btw, the main takeaway here is to use absolute paths whenever in doubt.

**Closed by voldemortX** 2022-02-03 12:10 UTC
Labels: question, lane detection
