### ISSUE TITLE
what's the "detect_dir" in eval.sh?

### ISSUE THREAD

**Issue by hanzhy-code** [voldemortX/pytorch-auto-drive#17] opened 2021-05-23 12:51 UTC
I want to evaluate the test set with CULane official scripts. But I don't understand the meaning of 'detect_dir' in tool/culane_evaluation/eval.sh.Can you tell me? Thanks!

**Comment by voldemortX** [comment] 2021-05-23 13:02
@hanzhy-code The `detect_dir` is where your predicted lanes (txt files) are (so that CULane official script can compare them with ground truth). 
In practice, you don't really need to mind that variable, since it is set as the default place where our evaluation scripts predict and save lanes.

**Comment by hanzhy-code** [comment] 2021-05-23 13:19
Thank you for your reply. I know it. The problem is that I use the weights you provide to predict the CULane and I want to evaluate it. But the results of tp and fn are zero,  I can't find the problem. Can you help me? Thanks!

The details are as follows：

list_im_file: /media/hzy/double-system/dataset/CULane/list/test_split/test0_normal.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 32672 fn: 0
no ground truth positive
finished process file
precision: 0
recall: -1
Fmeasure: 0

list_im_file: /media/hzy/double-system/dataset/CULane/list/test_split/test1_crowd.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 27416 fn: 0
no ground truth positive
finished process file
precision: 0
recall: -1
Fmeasure: 0

.......
list_im_file: /media/hzy/double-system/dataset/CULane/list/test_split/test8_night.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 0 fp: 19461 fn: 0
no ground truth positive
finished process file
precision: 0
recall: -1
Fmeasure: 0
----------------------------------
Traceback (most recent call last):
  File "cal_total.py", line 27, in <module>
    recall = tp / (tp + fn)
ZeroDivisionError: division by zero

**Comment by voldemortX** [comment] 2021-05-23 13:24
That seems weird. May I ask the filename of the weights that you download? And what is the exact commands you used for predicting lanes and evaluation?

**Comment by hanzhy-code** [comment] 2021-05-23 13:39
The filename of the weights is erfnet_scnn_culane_20210206.pt .
The exact commands is:
 python main_landec.py --state=2 --continue-from=./erfnet_scnn_culane_20210206.pt --dataset=culane --batch-size=4 --method=scnn --exp-name=hzy --mixed-precision
I check the  'output' directory, there are driver_37_30frame,driver_100_30frame and driver_193_30frame.There are the results of the predict. But some txt files are empty(there is no lanes?), others are the predict of the lanes.

**Comment by voldemortX** [comment] 2021-05-23 13:45
@hanzhy-code Some txts can be empty (there are no-lane images). But in your description, every setting seems correct, let me try and reproduce this.

**Comment by cedricgsh** [comment] 2021-05-23 14:12
Could you share the contents of  `eval.sh` in tool/culane_evaluation/?

**Comment by hanzhy-code** [comment] 2021-05-23 14:23
@cedricgsh I changed the code in two place, I have noted them.
 The contents of eval.sh in tool/culane_evaluation are as follows:
#!/bin/bash
root=../../
**data_dir=/media/hzy/double-system/dataset/CULane   # This is the path of the datasets in my computer.**
exp=$1
detect_dir=../../output/


# These can not be changed
w_lane=30;
iou=0.5;  # Set iou to 0.3 or 0.5
im_w=1640
im_h=590
frame=1
**list0=${data_dir}/list/test_split/test0_normal.txt   # I add '/' after  {data_dir}**
list1=${data_dir}/list/test_split/test1_crowd.txt
list2=${data_dir}/list/test_split/test2_hlight.txt
list3=${data_dir}/list/test_split/test3_shadow.txt
list4=${data_dir}//test_split/test4_noline.txt
list5=${data_dir}/list/test_split/test5_arrow.txt
list6=${data_dir}/list/test_split/test6_curve.txt
list7=${data_dir}/list/test_split/test7_cross.txt
list8=${data_dir}/list/test_split/test8_night.txt
out0=./output/out0_normal.txt
out1=./output/out1_crowd.txt
out2=./output/out2_hlight.txt
out3=./output/out3_shadow.txt
out4=./output/out4_noline.txt
out5=./output/out5_arrow.txt
out6=./output/out6_curve.txt
out7=./output/out7_cross.txt
out8=./output/out8_night.txt
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list0 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out0
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list1 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out1
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list2 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out2
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list3 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out3
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list4 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out4
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list5 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out5
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list6 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out6
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list7 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out7
./evaluate -a $data_dir -d $detect_dir -i $data_dir -l $list8 -w $w_lane -t $iou -c $im_w -r $im_h -f $frame -o $out8
cat ./output/out*.txt>./output/${exp}_iou${iou}_split.txt

**Comment by hanzhy-code** [comment] 2021-05-23 14:35
@voldemortX @cedricgsh Thank you very much. I've found my own mistakes. I change contents that can't be changed in the eval.sh.  I added '/' after {data_dir}, so it can't work. I modified it and now it works.

**Comment by voldemortX** [comment] 2021-05-23 15:57
Since the problem is resolved, I'll close this for now. Feel free to reopen if you have further questions.

**Closed by voldemortX** 2021-05-23 15:57 UTC
Labels: lane detection, question
