### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'to'

### ISSUE THREAD

**Issue by hanzhy-code** [voldemortX/pytorch-auto-drive#21] opened 2021-06-02 05:15 UTC
when I use the argument(val-num-steps), the error occurred(AttributeError: 'tuple' object has no attribute 'to').
The full command is  as follow:
 python main_landec.py --epochs=50 --lr=0.2 --batch-size=4 --dataset=tusimple --method=baseline --backbone=erfnet --mixed-precision --exp-name=111  --val-num-steps=2

I'd like to make sure if it should change 'image_set='val' ' to 'image_set='valfast'' in 178 line in all_utils_landec.py.

**Comment by voldemortX** [comment] 2021-06-02 05:27
@hanzhy-code It is indeed a bug, the script is reproduceable. I'll investigate how did this happen.

**Comment by voldemortX** [comment] 2021-06-02 05:38
> I'd like to make sure if it should change 'image_set='val' ' to 'image_set='valfast'' in 178 line in all_utils_landec.py.

Yes, this should be the right fix. I've updated the code.
The reason for this bug is probably because when I differentiated `val` and `valfast`, I forgot to change this line of code.

**Comment by hanzhy-code** [comment] 2021-06-02 06:46
@voldemortX Thank you for your reply. Your work is great. I've learned a lot from it

**Comment by voldemortX** [comment] 2021-06-02 07:02
You're welcome! I'm closing this issue since the bug is fixed.

A side note, I don't think `--val-num-steps=2` is realistic, since it is step, not epoch.

**Closed by voldemortX** 2021-06-02 07:02 UTC
Labels: bug, lane detection

**Comment by hanzhy-code** [comment] 2021-06-02 07:08
Yes, I just for testing the code.
