### ISSUE TITLE
Can't pickle local object 'BezierSampler.get_bezier_coefficient.<locals>.<lambda>'

### ISSUE THREAD

**Issue by Zhuanglong2** [voldemortX/pytorch-auto-drive#113] opened 2022-09-09 03:49 UTC
In the windows10, I meet the following problem.

D:\Users\409\Anaconda3\envs\pad\python.exe F:/PycharmProjects/pytorch-auto-drive-master/main_landet.py
D:\Users\409\Anaconda3\envs\pad\lib\site-packages\torch\package\_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy.core._multiarray_umath' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
F:\PycharmProjects\pytorch-auto-drive-master\utils\models\lane_detection\laneatt.py:22: UserWarning: Can't complie line nms op for LaneATT. Set verbose=True for load in /utils/csrc/apis.py L9 for details.
Loaded torchvision ImageNet pre-trained weights V1.
Not using distributed mode
cuda
Traceback (most recent call last):
  File "F:/PycharmProjects/pytorch-auto-drive-master/main_landet.py", line 65, in <module>
    runner.run()
  File "F:\PycharmProjects\pytorch-auto-drive-master\utils\runners\lane_det_trainer.py", line 35, in run
    for i, data in enumerate(self.dataloader, 0):
  File "D:\Users\409\Anaconda3\envs\pad\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "D:\Users\409\Anaconda3\envs\pad\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Users\409\Anaconda3\envs\pad\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "D:\Users\409\Anaconda3\envs\pad\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Users\409\Anaconda3\envs\pad\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Users\409\Anaconda3\envs\pad\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Users\409\Anaconda3\envs\pad\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Users\409\Anaconda3\envs\pad\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BezierSampler.get_bezier_coefficient.<locals>.<lambda>'

**Comment by voldemortX** [comment] 2022-09-09 05:20
@Zhuanglong2 Hi! Did you launch a training? can you provide the config file for your model, and some info about your local machine? e.g., CPU, GPU, memory

**Comment by voldemortX** [comment] 2022-09-09 05:24
Also, I think your error message includes something about a numpy error? It could be related.

**Comment by Zhuanglong2** [comment] 2022-09-09 11:51
> @Zhuanglong2你好！你开始培训了吗？你能提供你的模型的配置文件，以及关于你本地机器的一些信息吗？例如，CPU、GPU、内存

Thank you for your responce. I have addressed this problem by setting"numer works = 0".

**Comment by Zhuanglong2** [comment] 2022-09-09 11:53
When i run "lane_video.py", i meet this problem"RuntimeError: input must be contiguous". Then, I debug this code, and i find the problem appears in "flipped = self.proj2_conv(flipped, feature)". This is DCN_V2_Ref.

**Comment by voldemortX** [comment] 2022-09-09 12:44
> When i run "lane_video.py", i meet this problem"RuntimeError: input must be contiguous". Then, I debug this code, and i find the problem appears in "flipped = self.proj2_conv(flipped, feature)". This is DCN_V2_Ref.

Could you provide the exact command so I can try reproduce this? 
Usually this kind of problems can be solved by adding `.contiguous()` in proper places.

**Comment by Zhuanglong2** [comment] 2022-09-09 12:59
Thank you. I just run "lane_video.py" by following the"VISUALIZATION.md", and meet this problem. W[hen i DEBUG, i find that the code stops in "modulated_deform_conv.py".In this part, I find it have not class "apply".
![QQ图片20220909205722](https://user-images.githubusercontent.com/58128328/189355534-45c1bf93-f2e3-49e9-b37b-45ed739c04d1.png)

**Comment by voldemortX** [comment] 2022-09-09 13:17
@Zhuanglong2 Could you try changing this line:
https://github.com/voldemortX/pytorch-auto-drive/blob/2b0d5ec5f7536c9d2d2b6d8498718a8fca2ab276/utils/datasets/video.py#L28

to:

```
        images = images[..., [2, 1, 0]].permute(0, 3, 1, 2).contiguous() / 255.0  # BHWC-rgb uint8 -> BCHW-rgb float
```

**Comment by Zhuanglong2** [comment] 2022-09-12 03:45
> @Zhuanglong2 Could you try changing this line:
> 
> https://github.com/voldemortX/pytorch-auto-drive/blob/2b0d5ec5f7536c9d2d2b6d8498718a8fca2ab276/utils/datasets/video.py#L28
> 
> to:
> 
> ```
>         images = images[..., [2, 1, 0]].permute(0, 3, 1, 2).contiguous() / 255.0  # BHWC-rgb uint8 -> BCHW-rgb float
> ```
> 
> In my machine, without this change I can see a harmless warning for `mixed memory format`. However, with or without this change the code can still run properly.

Tank you very much! I have addressed this problem. In fact, my coding environment is windows 10, so i meet some problems. But my friend using Ubuntu has not problems.  Your open-source framework works great! Moreover, I have watched your video of this paper, and i am shocked that you are only graduate student! In the future, we will continue lane detection task following your footsteps. In the last, Happy Mid-Autumn Festival!

**Comment by voldemortX** [comment] 2022-09-12 03:53
Thanks for your interest in our work! Happy Mid-Autumn Festival!

**Comment by voldemortX** [comment] 2023-04-01 03:30
This issue seems to be addressed. I'll close it for now. Feel free to continue commenting for reopen/open a new one.

**Closed by voldemortX** 2023-04-01 03:30 UTC
Labels: question, lane detection
